# permissions for end users to edit simplegoappdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: simplegoappdeployment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: simple-go-app-k8s-operator
    app.kubernetes.io/part-of: simple-go-app-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: simplegoappdeployment-editor-role
rules:
- apiGroups:
  - simple-go-app-k8s-operator.jonasbe.de
  resources:
  - simplegoappdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - simple-go-app-k8s-operator.jonasbe.de
  resources:
  - simplegoappdeployments/status
  verbs:
  - get
