# permissions for end users to view simplegoappdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: simplegoappdeployment-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: simple-go-app-k8s-operator
    app.kubernetes.io/part-of: simple-go-app-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: simplegoappdeployment-viewer-role
rules:
- apiGroups:
  - simple-go-app-k8s-operator.jonasbe.de
  resources:
  - simplegoappdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - simple-go-app-k8s-operator.jonasbe.de
  resources:
  - simplegoappdeployments/status
  verbs:
  - get
